name: Qodana Code Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qodana:
    name: Run Qodana Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.1
        with:
          args: "--baseline,qodana.sarif.json"

      - name: Upload Qodana Report
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana.sarif.json

      - name: Publish Qodana Annotations
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: qodana.sarif.json
