name: Build and Run Tests

on:
  pull_request:

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            python-cache-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest --junit-xml=build/test-results/test/TEST-results.xml --verbose
        continue-on-error: true  # Ensures that test results are collected even if some tests fail

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: always()  # Always run this step even if tests fail
        with:
          name: junit-test-results
          path: build/test-results/test/TEST-results.xml
          retention-days: 1