name: Selenium Tests

on:
  workflow_dispatch: # Allows running manually
  schedule:
    - cron: '0 0 * * *' # Run each day on 00:00 UTC

jobs:
  selenium-tests:
    runs-on: macos-latest
    env:
      DEV_URL: ${{ vars.DEV_URL }}
      STAG_URL: ${{ vars.STAG_URL }}

    permissions:
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Chrome and WebDriver if not already installed
        run: |
          if ! command -v google-chrome &>/dev/null; then
            echo "Installing Chrome"
            brew install --cask google-chrome
          else
            echo "Chrome is already installed"
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pytest pytest-html

      - name: Run tests
        run: |
          python -m pytest --verbose --junit-xml=test-results.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/test-results.xml'
          detailed_summary: true
          include_passed: true